version: '3.1'

services:
  frontend:
    build: ./frontend
    restart: unless-stopped
    links:
      - api
  api:
    build: ./api
    restart: unless-stopped
    links:
      - postgres
    ports:
      - "8000:6000"
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: feather
      POSTGRES_PASSWORD: feather