version: '3.1'

services:
  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
  api:
    build: ./api
    ports:
      - "3030:3030"
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: feather
      POSTGRES_PASSWORD: feather